- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt:
    update_cache: yes

- name: Upgrade all packages on servers
  apt:
    upgrade: yes

- name: Install dependencies
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  command: npm install pm2 -g