version: 2.1

orbs:
  slack: circleci/slack@4.10.1

commands:
  notify_slack_fails:
    parameters:
      on-success:
        description: Notify also on-success
        type: boolean
        default: false
    steps:
      - slack/notify:
          event: fail
          mentions: '@Mohamed Raslan'
          template: basic_fail_1
      - when:
          condition: << parameters.on-success >>
          steps:
            - slack/notify:
                event: pass
                template: basic_success_1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - notify_slack_fails

  build-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - notify_slack_fails

  test-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Test front-end
          command: |
            cd frontend
            npm install
            npm run test
      - notify_slack_fails

  test-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Test back-end
          command: |
            cd backend
            npm install
            npm run test
      - notify_slack_fails

  scan-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Scan front-end
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - notify_slack_fails

  scan-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Scan back-end
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical
      - notify_slack_fails

workflows:
  default:
    jobs:
      - build-frontend:
          context: UdaPeopleSuperPower
      - build-backend:
          context: UdaPeopleSuperPower
      - test-frontend:
          context: UdaPeopleSuperPower
          requires: [build-frontend]
      - test-backend:
          context: UdaPeopleSuperPower
          requires: [build-backend]
      - scan-frontend:
          context: UdaPeopleSuperPower
          requires: [build-frontend]
      - scan-backend:
          context: UdaPeopleSuperPower
          requires: [build-backend]
